<?php
/**
 * Stripe Data API — Always serves from cache for instant response
 * Cache is generated by cache_stripe_data.php via CLI/cron
 */
header('Content-Type: application/json');

$accounts = require __DIR__ . '/stripe_config.php';

$account = isset($_GET['account']) ? $_GET['account'] : '';
if (!isset($accounts[$account])) {
    echo json_encode(['error' => 'Invalid account. Use: au, us, th, connect']);
    exit;
}

$timezone = $accounts[$account]['timezone'] ?? 'Australia/Queensland';
date_default_timezone_set($timezone);

// Support custom date range OR preset days
$customStart = isset($_GET['start']) ? $_GET['start'] : '';
$customEnd = isset($_GET['end']) ? $_GET['end'] : '';
$days = isset($_GET['days']) ? intval($_GET['days']) : 7;
if ($days < 1) $days = 7;
$isCustomRange = ($customStart !== '' && $customEnd !== '');

if ($isCustomRange) {
    $days = max(1, (int)((strtotime($customEnd) - strtotime($customStart)) / 86400) + 1);
}

$cacheDir = __DIR__ . '/cache';
$cacheMap = [
    7   => '7days',
    28  => '28days',
    90  => '90days',
    180 => '180days',
    365 => '365days',
];

$cacheName = null;
if (!$isCustomRange && isset($cacheMap[$days])) {
    $cacheName = $cacheMap[$days];
} elseif (!$isCustomRange && $days > 365) {
    $cacheName = 'alltime';
} elseif ($isCustomRange && $customStart === '2020-01-01' && $customEnd === date('Y-m-d')) {
    $cacheName = 'alltime';
}

$cacheFile = $cacheName ? ($cacheDir . "/{$account}_{$cacheName}.json") : '';
$cacheTtl = 0;
if ($cacheName === '7days' || $cacheName === '28days') {
    $cacheTtl = 300;
} elseif ($cacheName === '90days' || $cacheName === '180days') {
    $cacheTtl = 1800;
} elseif ($cacheName === '365days' || $cacheName === 'alltime') {
    $cacheTtl = 3600;
}

if ($cacheFile && file_exists($cacheFile)) {
    $cacheAge = time() - filemtime($cacheFile);
    $cached = file_get_contents($cacheFile);
    if ($cached && $cacheAge <= $cacheTtl) {
        $cachedData = json_decode($cached, true);
        if (is_array($cachedData)) {
            if (!isset($cachedData['debug']) || !is_array($cachedData['debug'])) {
                $cachedData['debug'] = [];
            }
            $cachedData['debug']['source'] = 'cache';
            $cachedData['debug']['cache_age_seconds'] = $cacheAge;
            echo json_encode($cachedData, JSON_UNESCAPED_UNICODE);
            exit;
        }
        echo $cached;
        exit;
    }
}

// No cache available — fallback to real-time query
ini_set('memory_limit', '1G');
set_time_limit(240);

require_once __DIR__ . '/../../vendor/autoload.php';

$sk = $accounts[$account]['sk'];
$currency = $accounts[$account]['currency'];
$primaryCur = strtolower($currency);
$stripe = new \Stripe\StripeClient($sk);
$isConnect = ($account === 'connect');

$now = time();
$todayStart = strtotime('today 00:00:00');
$yesterdayStart = strtotime('yesterday 00:00:00');

if ($customStart && $customEnd) {
    $periodStart = strtotime($customStart . ' 00:00:00');
    $periodEnd = strtotime($customEnd . ' 23:59:59');
    $days = max(1, (int)(($periodEnd - $periodStart) / 86400) + 1);
} else {
    $periodStart = strtotime("-" . ($days - 1) . " days 00:00:00");
    $periodEnd = $now;
}
$prevPeriodStart = $periodStart - ($periodEnd - $periodStart);
$skipDaily = ($days > 365);

$result = [];

try {

// 1. Balance (multi-currency for Connect)
$balance = $stripe->balance->retrieve();
$availableAmount = 0; $pendingAmount = 0;
$balanceByCurrency = [];
foreach ($balance->available as $b) {
    $cur = strtoupper($b->currency);
    if (!isset($balanceByCurrency[$cur])) $balanceByCurrency[$cur] = ['available' => 0, 'pending' => 0];
    $balanceByCurrency[$cur]['available'] += $b->amount / 100;
    $availableAmount += $b->amount;
}
foreach ($balance->pending as $b) {
    $cur = strtoupper($b->currency);
    if (!isset($balanceByCurrency[$cur])) $balanceByCurrency[$cur] = ['available' => 0, 'pending' => 0];
    $balanceByCurrency[$cur]['pending'] += $b->amount / 100;
    $pendingAmount += $b->amount;
}
$result['balance'] = ['available' => $availableAmount / 100, 'pending' => $pendingAmount / 100, 'currency' => $currency, 'by_currency' => $balanceByCurrency];

// 2. Payouts — ดึงตามช่วงเวลาที่เลือก + upcoming
$result['payouts'] = [];
$seenIds = [];

$upcomingPayouts = $stripe->payouts->all(['limit' => 100, 'arrival_date' => ['gte' => strtotime('today')]]);
foreach ($upcomingPayouts->data as $p) {
    if (isset($seenIds[$p->id])) continue;
    $seenIds[$p->id] = true;
    $result['payouts'][] = [
        'id' => $p->id, 'amount' => $p->amount / 100, 'currency' => strtoupper($p->currency),
        'status' => $p->status, 'arrival_date' => date('Y-m-d', $p->arrival_date), 'created' => date('Y-m-d H:i', $p->created)
    ];
}

$periodPayouts = $stripe->payouts->all(['limit' => 100, 'created' => ['gte' => $periodStart, 'lt' => $periodEnd + 86400]]);
foreach ($periodPayouts->autoPagingIterator() as $p) {
    if (isset($seenIds[$p->id])) continue;
    $seenIds[$p->id] = true;
    $result['payouts'][] = [
        'id' => $p->id, 'amount' => $p->amount / 100, 'currency' => strtoupper($p->currency),
        'status' => $p->status, 'arrival_date' => date('Y-m-d', $p->arrival_date), 'created' => date('Y-m-d H:i', $p->created)
    ];
}

usort($result['payouts'], function($a, $b) {
    return strtotime($b['created']) - strtotime($a['created']);
});
// หา next payout จาก upcoming (arrival_date เร็วที่สุด)
$nextExpectedPayout = 0; $payoutExpectedDate = '';
$nearestArrival = PHP_INT_MAX;
foreach ($upcomingPayouts->data as $p) {
    if ($p->arrival_date < $nearestArrival) {
        $nearestArrival = $p->arrival_date;
        $nextExpectedPayout = $p->amount / 100;
        $payoutExpectedDate = date('M j', $p->arrival_date);
    }
}
if ($nextExpectedPayout === 0) {
    foreach ($result['payouts'] as $po) {
        if (in_array($po['status'], ['in_transit', 'pending'])) {
            $nextExpectedPayout = $po['amount'];
            $payoutExpectedDate = date('M j', strtotime($po['arrival_date']));
            break;
        }
    }
}
if ($nextExpectedPayout === 0 && $pendingAmount > 0) {
    $nextExpectedPayout = $pendingAmount / 100;
    $estDate = strtotime('+2 days'); $dow = date('N', $estDate);
    if ($dow == 6) $estDate = strtotime('+2 days', $estDate);
    if ($dow == 7) $estDate = strtotime('+1 day', $estDate);
    $payoutExpectedDate = date('M j', $estDate);
} elseif ($nextExpectedPayout === 0 && $availableAmount > 0) {
    $nextExpectedPayout = $availableAmount / 100;
    $payoutExpectedDate = '';
}
$result['nextPayout'] = $nextExpectedPayout;
$result['payoutExpectedDate'] = $payoutExpectedDate;

// 3. Balance Transactions
$dailyGross = []; $dailyNet = [];
if (!$skipDaily) {
    for ($t = $periodStart; $t <= $periodEnd; $t += 86400) { $d = date('M j', $t); $dailyGross[$d] = 0; $dailyNet[$d] = 0; }
}
$todayGross = 0; $yesterdayGross = 0;
$grossTotal = 0; $netTotal = 0; $feeTotal = 0; $refundTotal = 0;
$prevGross = 0; $prevNet = 0; $txnCount = 0;
$debugTypes = []; // DEBUG: track transaction types and amounts

$txnList = $stripe->balanceTransactions->all([
    'limit' => 100, 'created' => ['gte' => $prevPeriodStart, 'lt' => $periodEnd + 86400]
]);
foreach ($txnList->autoPagingIterator() as $tx) {
    $txnCount++;
    $amt = $tx->amount / 100; $net = $tx->net / 100; $fee = $tx->fee / 100;
    $ts = $tx->created; $type = $tx->type;

    // DEBUG: track all types
    if ($ts >= $periodStart) {
        if (!isset($debugTypes[$type])) $debugTypes[$type] = ['count' => 0, 'amount' => 0, 'net' => 0, 'fee' => 0];
        $debugTypes[$type]['count']++;
        $debugTypes[$type]['amount'] += $amt;
        $debugTypes[$type]['net'] += $net;
        $debugTypes[$type]['fee'] += $fee;
    }

    // Include transfer/revenue_share/application_fee for Connect accounts
    $isGrossType = ($type === 'charge' || $type === 'payment' || $type === 'transfer'
        || ($isConnect && ($type === 'revenue_share' || $type === 'application_fee')));
    if ($ts >= $periodStart) {
        if ($isGrossType) {
            $grossTotal += $amt; $netTotal += $net; $feeTotal += $fee;
            if (!$skipDaily) { $day = date('M j', $ts); if (isset($dailyGross[$day])) $dailyGross[$day] += $amt; if (isset($dailyNet[$day])) $dailyNet[$day] += $net; }
        } elseif ($type === 'refund') { $refundTotal += abs($amt); }
        if ($ts >= $todayStart && $isGrossType) $todayGross += $amt;
        if ($ts >= $yesterdayStart && $ts < $todayStart && $isGrossType) $yesterdayGross += $amt;
    } elseif ($ts >= $prevPeriodStart && $ts < $periodStart) {
        if ($isGrossType) { $prevGross += $amt; $prevNet += $net; }
    }
}
unset($txnList, $tx);

$grossChange = $prevGross > 0 ? round(($grossTotal - $prevGross) / $prevGross * 100, 1) : 0;
$netChange = $prevNet > 0 ? round(($netTotal - $prevNet) / $prevNet * 100, 1) : 0;
$result['today'] = ['gross' => round($todayGross, 2), 'yesterday' => round($yesterdayGross, 2), 'time' => date('g:i A')];
$result['grossVolume'] = ['total' => round($grossTotal, 2), 'previous' => round($prevGross, 2), 'change' => $grossChange, 'daily' => $dailyGross];
$result['netVolume'] = ['total' => round($netTotal, 2), 'previous' => round($prevNet, 2), 'change' => $netChange, 'daily' => $dailyNet];
$result['feeTotal'] = round($feeTotal, 2);
$result['refundTotal'] = round($refundTotal, 2);

// 4. Charges
$failedPayments = []; $succeededTotal = 0; $failedTotal = 0; $blockedTotal = 0;
$uncapturedTotal = 0; $refundedTotal2 = 0; $succeededCount = 0; $failedCount = 0;
$seenPISucc = []; $seenPIFail = []; $customerSpend = [];
$periodCharges = $stripe->charges->all(['limit' => 100, 'created' => ['gte' => $periodStart, 'lt' => $periodEnd + 86400]]);
$pcCount = 0;
foreach ($periodCharges->autoPagingIterator() as $c) {
    $pcCount++;
    $amt = $c->amount / 100;
    $chargeCur = strtolower($c->currency);
    $custEmail = $c->billing_details->email ?: ($c->receipt_email ?: '');
    $pi = $c->payment_intent ?: '';
    if ($c->status === 'succeeded') {
        $isDupe = false;
        if ($pi) { if (isset($seenPISucc[$pi])) $isDupe = true; else $seenPISucc[$pi] = true; }
        if (!$isDupe && ($isConnect || $chargeCur === $primaryCur)) {
            if ($c->captured) { $succeededTotal += $amt; $succeededCount++; if ($c->refunded) $refundedTotal2 += ($c->amount_refunded ?? 0) / 100; }
            else $uncapturedTotal += $amt;
            $custId = $c->customer ?: '';
            if ($custId) {
                $custName = $c->billing_details->name ?: '';
                if (!isset($customerSpend[$custId])) $customerSpend[$custId] = ['email' => $custEmail, 'name' => $custName, 'amount' => 0];
                $customerSpend[$custId]['amount'] += $amt;
            }
        }
    } elseif ($c->status === 'failed') {
        $isDupe = false;
        if ($pi) { if (isset($seenPIFail[$pi])) $isDupe = true; else $seenPIFail[$pi] = true; }
        if (!$isDupe && ($isConnect || $chargeCur === $primaryCur)) {
            $failedTotal += $amt; $failedCount++;
            if (count($failedPayments) < 4) {
                $failedPayments[] = ['id' => $c->id, 'amount' => round($amt, 2), 'created' => date('M j, Y', $c->created), 'description' => $c->description ?: 'Payment'];
            }
        }
    }
}
unset($periodCharges, $c, $seenPISucc, $seenPIFail);
$result['payments'] = ['succeeded' => round($succeededTotal, 2), 'failed' => round($failedTotal, 2), 'blocked' => round($blockedTotal, 2), 'uncaptured' => round($uncapturedTotal, 2), 'refunded' => round($refundedTotal2, 2), 'succeeded_count' => $succeededCount, 'failed_count' => $failedCount];
$result['failedPayments'] = array_slice($failedPayments, 0, 4);

// Top customers
$result['topCustomers'] = [];
if (!empty($customerSpend)) {
    uasort($customerSpend, function($a, $b) { return $b['amount'] <=> $a['amount']; });
    $i = 0;
    foreach ($customerSpend as $cid => $info) {
        if ($i >= 5) break;
        $result['topCustomers'][] = ['id' => $cid, 'name' => $info['name'] ?: 'Unknown', 'email' => $info['email'] ?: '', 'amount' => round($info['amount'], 2)];
        $i++;
    }
}
unset($customerSpend);

// 5. Subscriptions (MRR)
$activeSubCount = 0; $mrr = 0; $subCount = 0; $newSubMrr = 0;
$mrrStatuses = ['active', 'trialing', 'past_due'];
foreach ($mrrStatuses as $subStatus) {
    $subList = $stripe->subscriptions->all(['status' => $subStatus, 'limit' => 100]);
    foreach ($subList->autoPagingIterator() as $s) {
        $subCount++;
        if ($subStatus === 'active') $activeSubCount++;
        $subMrr = 0;
        if (isset($s->items->data[0]->price)) {
            $price = $s->items->data[0]->price;
            $unitAmt = ($price->unit_amount ?? 0) / 100;
            $interval = $price->recurring->interval ?? 'month';
            $intervalCount = $price->recurring->interval_count ?? 1;
            if ($interval === 'year') $unitAmt = $unitAmt / (12 * $intervalCount);
            elseif ($interval === 'week') $unitAmt = $unitAmt * (52 / 12) / $intervalCount;
            elseif ($interval === 'day') $unitAmt = $unitAmt * (365 / 12) / $intervalCount;
            else $unitAmt = $unitAmt / $intervalCount;
            $qty = $s->items->data[0]->quantity ?? 1;
            $subMrr = $unitAmt * $qty;
        }
        $mrr += $subMrr;
        if ($s->created >= $periodStart) $newSubMrr += $subMrr;
    }
    unset($subList, $s);
}
$result['subscriptions'] = ['active_count' => $activeSubCount];
$prevMrr = $mrr - $newSubMrr; if ($prevMrr < 0) $prevMrr = 0;
$mrrChange = $prevMrr > 0 ? round(($mrr - $prevMrr) / $prevMrr * 100, 1) : 0;
$result['mrr'] = ['total' => round($mrr, 2), 'previous' => round($prevMrr, 2), 'change' => $mrrChange];

// 6. Customers / Connected Accounts
$newCustCount = 0; $dailyNewCust = [];
if (!$skipDaily) { for ($t = $periodStart; $t <= $periodEnd; $t += 86400) { $d = date('M j', $t); $dailyNewCust[$d] = 0; } }

if ($isConnect) {
    // For Connect: count connected accounts instead of customers
    // Fetch all accounts and filter by created date manually using toArray()
    $acctList = $stripe->accounts->all(['limit' => 100]);
    $prevCustCount = 0;
    foreach ($acctList->autoPagingIterator() as $acct) {
        $acctArr = $acct->toArray();
        $acctCreated = $acctArr['created'] ?? 0;
        if ($acctCreated >= $periodStart && $acctCreated < $periodEnd + 86400) {
            $newCustCount++;
            if (!$skipDaily) { $d = date('M j', $acctCreated); if (isset($dailyNewCust[$d])) $dailyNewCust[$d]++; }
        } elseif ($acctCreated >= $prevPeriodStart && $acctCreated < $periodStart) {
            $prevCustCount++;
        }
    }
    unset($acctList, $acct, $acctArr);
} else {
    $custList = $stripe->customers->all(['limit' => 100, 'created' => ['gte' => $periodStart, 'lt' => $periodEnd + 86400]]);
    foreach ($custList->autoPagingIterator() as $cu) { $newCustCount++; if (!$skipDaily) { $d = date('M j', $cu->created); if (isset($dailyNewCust[$d])) $dailyNewCust[$d]++; } }
    unset($custList, $cu);
    $prevCustCount = 0;
    $prevCustList = $stripe->customers->all(['limit' => 100, 'created' => ['gte' => $prevPeriodStart, 'lt' => $periodStart]]);
    foreach ($prevCustList->autoPagingIterator() as $cu) { $prevCustCount++; }
    unset($prevCustList, $cu);
}
$newCustChange = $prevCustCount > 0 ? round(($newCustCount - $prevCustCount) / $prevCustCount * 100, 0) : 0;
$result['newCustomers'] = ['count' => $newCustCount, 'previous' => $prevCustCount, 'change' => $newCustChange, 'daily' => $dailyNewCust];

$curSymbolMap = ['usd'=>'$','aud'=>'A$','thb'=>'฿','gbp'=>'£','eur'=>'€','nzd'=>'NZ$'];
$result['currencySymbol'] = $curSymbolMap[$primaryCur] ?? strtoupper($currency);
$result['currencyCode'] = strtoupper($currency);
$result['period'] = ['days' => $days, 'start' => date('M j', $periodStart), 'end' => date('M j', $periodEnd), 'timezone' => $timezone];
// Round debug type amounts
foreach ($debugTypes as &$dt) { $dt['amount'] = round($dt['amount'], 2); $dt['net'] = round($dt['net'], 2); $dt['fee'] = round($dt['fee'], 2); }
unset($dt);
$result['debug'] = [
    'balance_txns_fetched' => $txnCount, 'charges_fetched' => $pcCount,
    'subscriptions_fetched' => $subCount, 'customers_fetched' => $newCustCount + $prevCustCount,
    'memory_peak' => round(memory_get_peak_usage(true) / 1024 / 1024, 1) . 'MB',
    'time_seconds' => round(microtime(true) - $_SERVER['REQUEST_TIME_FLOAT'], 1),
    'source' => 'realtime',
    'txn_types' => $debugTypes,
    'period_start' => date('Y-m-d H:i:s', $periodStart),
    'period_end' => date('Y-m-d H:i:s', $periodEnd),
    'prev_period_start' => date('Y-m-d H:i:s', $prevPeriodStart)
];

// Save cache for future use
$result['cached_at'] = date('Y-m-d H:i:s');
if ($cacheFile) {
    if (!is_dir($cacheDir)) mkdir($cacheDir, 0755, true);
    file_put_contents($cacheFile, json_encode($result, JSON_UNESCAPED_UNICODE));
}

} catch (\Stripe\Exception\ApiErrorException $e) {
    echo json_encode(['error' => $e->getMessage()]);
    exit;
} catch (\Exception $e) {
    echo json_encode(['error' => 'Server error: ' . $e->getMessage()]);
    exit;
}

echo json_encode($result, JSON_UNESCAPED_UNICODE);
exit;
